### ISSUE TITLE
Can't get dotenv to work with the .env file in the root dir

### ISSUE THREAD

**Issue by jelleriecker** [jelleriecker/kotlin-assignment#1]
errorlog
`Exception in thread "main" io.github.cdimascio.dotenv.DotenvException: Malformed entry DB_HOST: db
        at io.github.cdimascio.dotenv.internal.DotenvParser.parse(DotenvParser.java:68)
        at io.github.cdimascio.dotenv.DotenvBuilder.load(DotenvBuilder.java:77)
        at io.memorix.user.DbConnectionKt.initDatabase(DbConnection.kt:16)
        at io.memorix.ApplicationKt.main(Application.kt:17)
        at io.memorix.ApplicationKt.main(Application.kt)
`

**Comment by jelleriecker** [comment]
dotenv is now working by replacing the values for docker compose (format key: value) to format key=value. need to find a way around this but for now it's working.
